### ISSUE TITLE
About the Replace all max pooling operation

### ISSUE THREAD

**Issue by zrl4836** [PeikeLi/Self-Correction-Human-Parsing#1]
Hello.  Thank you for sharing！
In the PPT about LIP Challenge say,replace all max pooling operation.
But it  still have  max pooling in the model.  
Is my understanding right? How much difference there is between using it and not using it。

**Comment by zrl4836** [comment]
https://github.com/PeikeLi/Self-Correction-Human-Parsing/blob/e449f4261f8377a64ceda3799b37807e3bddde35/model.py#L223

**Comment by charishnaidu** [comment]
The code works fine for lip dataset but if I choose either atr or pascal it's showing a runtime error as shown below.

Traceback (most recent call last):
  File "evaluate.py", line 144, in <module>
    main()
  File "evaluate.py", line 99, in main
    model.load_state_dict(state_dict)
  File "/home/harish/.pyenv/versions/schp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.decoder.conv4.weight: copying a param with shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
	size mismatch for module.decoder.conv4.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for module.fushion.3.weight: copying a param with shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
	size mismatch for module.fushion.3.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([18]).

Any hints to rectify this would be appreciated. Thanks in advance..

**Comment by zrl4836** [comment]
> The code works fine for lip dataset but if I choose either atr or pascal it's showing a runtime error as shown below.
> 
> Traceback (most recent call last):
> File "evaluate.py", line 144, in
> main()
> File "evaluate.py", line 99, in main
> model.load_state_dict(state_dict)
> File "/home/harish/.pyenv/versions/schp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for DataParallel:
> size mismatch for module.decoder.conv4.weight: copying a param with shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
> size mismatch for module.decoder.conv4.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([18]).
> size mismatch for module.fushion.3.weight: copying a param with shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
> size mismatch for module.fushion.3.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([18]).
> 
> Any hints to rectify this would be appreciated. Thanks in advance..

What is your command on  runtime ?

**Comment by PeikeLi** [comment]
> The code works fine for lip dataset but if I choose either atr or pascal it's showing a runtime error as shown below.
> 
> Traceback (most recent call last):
> File "evaluate.py", line 144, in
> main()
> File "evaluate.py", line 99, in main
> model.load_state_dict(state_dict)
> File "/home/harish/.pyenv/versions/schp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for DataParallel:
> size mismatch for module.decoder.conv4.weight: copying a param with shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
> size mismatch for module.decoder.conv4.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([18]).
> size mismatch for module.fushion.3.weight: copying a param with shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
> size mismatch for module.fushion.3.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([18]).
> 
> Any hints to rectify this would be appreciated. Thanks in advance..



> The code works fine for lip dataset but if I choose either atr or pascal it's showing a runtime error as shown below.
> 
> Traceback (most recent call last):
> File "evaluate.py", line 144, in
> main()
> File "evaluate.py", line 99, in main
> model.load_state_dict(state_dict)
> File "/home/harish/.pyenv/versions/schp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for DataParallel:
> size mismatch for module.decoder.conv4.weight: copying a param with shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
> size mismatch for module.decoder.conv4.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([18]).
> size mismatch for module.fushion.3.weight: copying a param with shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
> size mismatch for module.fushion.3.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([18]).
> 
> Any hints to rectify this would be appreciated. Thanks in advance..

@charishnaidu please check your cmd --dataset 'lip or atr or pascal' and make sure you choose the right corresponding checkpoint.

**Comment by zrl4836** [comment]
> > Hello. Thank you for sharing！
> > In the PPT about LIP Challenge say,replace all max pooling operation.
> > But it still have max pooling in the model.
> > Is my understanding right? How much difference there is between using it and not using it。
> 
> The boost is very little +/- 0.3. And we only use that in the challenge. Currently we only provide the original Resnet-101 version.

OK!
