### ISSUE TITLE
Paddle code link failure

### ISSUE THREAD

**Issue by LutaoChu** [PeikeLi/Self-Correction-Human-Parsing#10]
Homepage Paddle code link has been 404.
The newest link is https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/ACE2P

**Comment by PeikeLi** [comment]
Thank you for sharing. I have updated the links.

**Comment by h3clikejava** [comment]
Homepage Paddle code link has been 404.
The link is https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/ACE2P

哥们还是404呀

**Comment by LutaoChu** [comment]
这是静态图实现的ACE2P，已经迁移到这里了 https://github.com/PaddlePaddle/PaddleSeg/tree/develop/legacy/contrib/ACE2P
