### ISSUE TITLE
The implementation of InPlaceABNSync

### ISSUE THREAD

**Issue by luciaL** [PeikeLi/Self-Correction-Human-Parsing#13]
There are some differences in your implementation with the original  [ https://github.com/mapillary/inplace_abn](url)
I am not sure if your implememtation could work efficiently.
Have you test the two implementations?

**Comment by PeikeLi** [comment]
We have updated the InplaceABN implemented following https://github.com/mapillary/inplace_abn.
The former implementation is just an equivalent version for sorely evaluation to avoid the cuda compiling process.
