### ISSUE TITLE
RuntimeError while training

### ISSUE THREAD

**Issue by VyBui** [PeikeLi/Self-Correction-Human-Parsing#16]
Hello @PeikeLi,

I cloned your train code and config to my own dataset like LIP:

However, when I run `python train.py` this is what I have got:

![Screenshot from 2020-06-27 17-02-48](https://user-images.githubusercontent.com/15938335/85919735-53482c00-b898-11ea-88f6-fbf4a83cec0e.png)

I wanted to ask if this is my mistake?

**Comment by PeikeLi** [comment]
I suppose that you are training with your own dataset.  By default, the input dimensions are NCHW. Check it by yourself.

**Comment by VyBui** [comment]
@PeikeLi thank you for you reply, 

Yes, I am training with my own dataset, the error was the order of NCHW. I got the training running will see if it works.
