### ISSUE TITLE
 No such file or directory: './pretrain_model/resnet101-imagenet.pth'

### ISSUE THREAD

**Issue by kpkroy** [PeikeLi/Self-Correction-Human-Parsing#17]
Hello @PeikeLi 
Thank you for your contribution. 
I am getting the following error upon running train.py:

_Namespace(arch='resnet101', batch_size=16, cycle_epochs=10, data_dir='./data/LIP', epochs=150, eval_epochs=10, gpu='0,1,2', ignore_label=255, imagenet_pretrain='./pretrain_model/resnet101-imagenet.pth', input_size='473,473', lambda_c=0.1, lambda_e=1, lambda_s=1, learning_rate=0.007, log_dir='./log', model_restore='./log/checkpoint.pth.tar', momentum=0.9, num_classes=20, random_mirror=False, random_scale=False, schp_restore='./log/schp_checkpoint.pth.tar', schp_start=100, start_epoch=0, weight_decay=0.0005)
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    main()
  File "train.py", line 94, in main
    AugmentCE2P = networks.init_model(args.arch, num_classes=args.num_classes, pretrained=args.imagenet_pretrain)
  File "/home/runque/PycharmProjects/Self-Correction-Human-Parsing-master/networks/__init__.py", line 13, in init_model
    return __factory[name](*args, **kwargs)
  File "/home/runque/PycharmProjects/Self-Correction-Human-Parsing-master/networks/AugmentCE2P.py", line 336, in resnet101
    initialize_pretrained_model(model, settings, pretrained)
  File "/home/runque/PycharmProjects/Self-Correction-Human-Parsing-master/networks/AugmentCE2P.py", line 324, in initialize_pretrained_model
    saved_state_dict = torch.load(pretrained)
  File "/home/runque/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/runque/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/runque/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './pretrain_model/resnet101-imagenet.pth'_

A. 
I have not found pretrain_model directory within your code - is this something I should get from elsewhere?

B.
Before running simple_extractor, I would have to run train.py  - am I correct?

C. 
Am I correct in  assuming that I would get CHECKPOINT_PATH after running the above train.py   ?

Thanks

**Comment by VyBui** [comment]
@kpkroy 

1) you have to download the pre-trained Imagenet model from the readme. Then place it inside the pretrain_model folder.
2) @PeikeLi correct me if I am wrong here,  the simple_extractor is simply for visualization, from classes image-> color images, so you have to train the network got the model then use it to visualize, I believe it is written with the same purpose with the evaluate script
3) Yes, you are correct. However, I have found an issue in the training code that the `schp.save_checkpoint` has been changed to `schp.save_schp_checkpoint`. You need to fix it by yourself. 

regards,

**Comment by PeikeLi** [comment]
@VyBui Thank you for replying and pointing out the issue.

In addition, `simple_extractor.py` aims for someone who only wants to get the parsing result or intermediate feature representations with the given pre-trained models.

**Comment by kpkroy** [comment]
Thank you guys. Much appreciation.

**Comment by Stephenfang51** [comment]
> @kpkroy
> 
> 1. you have to download the pre-trained Imagenet model from the readme. Then place it inside the pretrain_model folder.
> 2. @PeikeLi correct me if I am wrong here,  the simple_extractor is simply for visualization, from classes image-> color images, so you have to train the network got the model then use it to visualize, I believe it is written with the same purpose with the evaluate script
> 3. Yes, you are correct. However, I have found an issue in the training code that the `schp.save_checkpoint` has been changed to `schp.save_schp_checkpoint`. You need to fix it by yourself.
> 
> regards,

Dear Sir 

where to download resnet101-imagenet.pth you mentioned, I did not see any imagenet pretrain model from README.md

**Comment by FraPochetti** [comment]
Indeed I cannot find the pretrained weights either.
Is this something we can get from `torchvision` given it's a simple ResNet101?

Or is this the [link](https://github.com/PeikeLi/Self-Correction-Human-Parsing/blob/eb84c432cc697f494d99662a05f2335eb2f26095/networks/backbone/resnet.py#L28)?
