### ISSUE TITLE
discussion about the performance improvement

### ISSUE THREAD

**Issue by gitbabyboy** [PeikeLi/Self-Correction-Human-Parsing#26]
Hi peike,

We have trained the model on our private dataset. We do observe a significant performance improvement compared to our baseline. However, the current implementation follows label refinement process with online averaging. Besides, we have also implemented a version following the original paper, which adopts a offline label update process. The performance is similar but the latter one is slightly better. Any idea why this would happen?

**Comment by PeikeLi** [comment]
Glad to hear that our method brings performance improvement. The current implementation adopts the online label refinement instead of calculating and updating the label after each cycle, which aims to code simplicity and readability. There will only be a negligible performance gap.

**Comment by gitbabyboy** [comment]
Thanks!
