### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hazel0504** [PeikeLi/Self-Correction-Human-Parsing#28]
Looks interesting - would like to try.  Is this MIT license?

**Comment by hazel0504** [comment]
Is this is open source?  One of the licenses in here apply?   https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by hazel0504** [comment]
If you intend to specify "No License" can you at least tell us?  https://choosealicense.com/no-permission/  
as I'm sure you know... 

No License
When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

**Comment by PeikeLi** [comment]
Sorry for the late response, the repo is under MIT license. Thank you for your interest in our work.
