### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by loveppdog** [PeikeLi/Self-Correction-Human-Parsing#3]
Can you send me the  train code to my email , pls? I want to retrain and modify upsample. 
My email: 0001xiapi@163.com
Thanks very much.

**Comment by generalhuy** [comment]
Hello Peike Li, your work is amazing, especially your ensemble learning method. Currently, I am doing a project in the LIP challenge with Deeplab v3+, which achieved about 57% accuracy, which is pretty low especially minor classes. Therefore, can you send me your training code to my email: [mxhuysnowy@gmail.com](mailto:mxhuysnowy@gmail.com), I want to learn more about your work. Thank you very much.

**Comment by PeikeLi** [comment]
@loveppdog 
Thank you for your interest in our work. Currently our work is still under review, the code will be released upon acceptance.

**Comment by VyBui** [comment]
dear @PeikeLi,

when will the code be released? 

Your work is really impressive! One more question though, do you mind to share the cloud strategy you use to do online training?
