### ISSUE TITLE
How to fine tune pretrained pascal person model on your own data?

### ISSUE THREAD

**Issue by rkhilnani9** [PeikeLi/Self-Correction-Human-Parsing#33]
Trying to use exp-schp-201908270938-pascal-person-part.pth model for fine tuning on data with number of classes = 3.

Where do I plug in the weights of the model?

Both --model-restore=./pretrain_model/exp-schp-201908270938-pascal-person-part.pth and --schp-restore=./pretrain_model/exp-schp-201908270938-pascal-person-part.pth are throwing errors. 

--imagenet-pretrain has to be ./pretrain_model/resnet101-imagenet.pth. So where does the weights of the pascal pretrained model fit in train.py?

**Comment by Julymycin** [comment]
Well, I think both  --model-restore and --schp-restore are used for resume training, not well fit for finetune, you can use the default value, and then, add:
`state_dict = torch.load(pre_ckpt)['state_dict']
    model.load_state_dict(state_dict)
    schp_model.load_state_dict(state_dict)`
after you initialize model and schp_model,pre_ckpt means the path to your pretrained weight such as exp-schp-201908270938-pascal-person-part.pth.
Hope it can work.

**Comment by rkhilnani9** [comment]
@Julymycin Thanks for your suggestion! I tried that, but I am getting this error :

size mismatch for module.decoder.conv4.weight: copying a param with shape torch.Size([7, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).

My data has 3 classes, and the pascal person dataset has 7. That can be the issue, but I'm struggling to figure out how to resolve. it.

**Comment by Julymycin** [comment]
@rkhilnani9 Well, there are two possibly helpful options for you.
1. use the 7 classes as default network and load the state_dict, then change this layer to 3 classes, initial it.
2. use your own 3 classes network, before you load the state_dict, locate the mismatch layer(s), change its shape or replace it with your custom(or random) tensor value.

**Comment by Stephenfang51** [comment]
@Julymycin  

Dear Sir

I followed your step and I can load LIP pretrained model so far, however the errors shows
```
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
> /home/liwei.fang/SCHP/train_qinzhou_pretrainfromlip.py(209)main()
-> preds = model(images)
```

I checked the model parameter and buffers on gpu using next(model.parameters()).is_cuda() and it return True
Did you sucessfully using pretrained model before ?
Thanks so much !

**Comment by Stephenfang51** [comment]
> @Julymycin
> 
> Dear Sir
> 
> I followed your step and I can load LIP pretrained model so far, however the errors shows
> 
> ```
> RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
> > /home/liwei.fang/SCHP/train_qinzhou_pretrainfromlip.py(209)main()
> -> preds = model(images)
> ```
> 
> I checked the model parameter and buffers on gpu using next(model.parameters()).is_cuda() and it return True
> Did you sucessfully using pretrained model before ?
> Thanks so much !

I just solved the problem, the error happend becuase I modified the final fusion layer conv outputs to 3 nodes, and the weight I changed is on cpu, so need to `model.to(device)`  afterall
