### ISSUE TITLE
about the run environment

### ISSUE THREAD

**Issue by newExplore-hash** [PeikeLi/Self-Correction-Human-Parsing#43]
i have installed Python = 3.6.7, PyTorch = 1.4.0, but when i run simple_extractor.py, there is a problem,

ninja: build stopped: subcommand failed.

can you provide some solutions for this error?
tks

**Comment by melih1996** [comment]
@newExplore-hash how did you solve the problem?

**Comment by soumyajit123dev** [comment]
> i have installed Python = 3.6.7, PyTorch = 1.4.0, but when i run simple_extractor.py, there is a problem,
> 
> ninja: build stopped: subcommand failed.
> 
> can you provide some solutions for this error?
> tks

I am getting same error while running simple_extractor.py. Please help me how to solve this error
