### ISSUE TITLE
Change display color

### ISSUE THREAD

**Issue by Yijia-Chen** [PeikeLi/Self-Correction-Human-Parsing#45]
I was wondering where I can change the colors to something different.

**Comment by PeikeLi** [comment]
@Yijia-Chen Hi the visualization color is added to the png via color palette https://github.com/PeikeLi/Self-Correction-Human-Parsing/blob/b1ba867941b7b9e7fe92431925839aac663a5936/evaluate.py#L198.

In brief, each pixel is in the image is the label id. The display color is defined by a customized color palette.

**Comment by Yijia-Chen** [comment]
Thank you!
