### ISSUE TITLE
How to create bounding box for each class?

### ISSUE THREAD

**Issue by akhil451** [PeikeLi/Self-Correction-Human-Parsing#48]
How can I create bounding boxes for the different classes? I was not able to find the pixel values for each label in the output segmentation map to create a bounding box for the different classes.

**Comment by PeikeLi** [comment]
Each pixel in the output maps denotes the ID of the predicted class. In this way, you can use simple solution (for example, find the x_min, x_max, y_min, y_max) to create the bounding box for each object.
