### ISSUE TITLE
How to change the backbone network to mobilenetv2

### ISSUE THREAD

**Issue by BruceLoveDecimal** [PeikeLi/Self-Correction-Human-Parsing#49]
I found some difficulties when using the code of mobilenetv2 in the file  named backbone, it seems some params went wrong? How can I fix it?

**Comment by h3clikejava** [comment]
How to do it my dear friend, can you share it?

**Comment by abhigoku10** [comment]
@BruceLoveDecimal  can you pls share the changes which you have made for mobilenetv2 architecture
