### ISSUE TITLE
class InPlaceABNSync(nn.Module):

### ISSUE THREAD

**Issue by tjpulkl** [PeikeLi/Self-Correction-Human-Parsing#5]
How do you use InPlaceABNsYNC in your project? I want train you code with Pytorch1.3! But I dont know how to use InPlaceABNSync and the usefulness of it. could you please tell me?

**Comment by PeikeLi** [comment]
@tjpulkl 
We adopt the implementation of InPlaceABNs from https://github.com/mapillary/inplace_abn. This implementation use leakyrelu as default activation function.
Currently we only release the inference code. To maintain consistency, we use the leaky relu and bn in pytorch in our code.

**Comment by tjpulkl** [comment]
Hi.
  thank you for your reply. would you please answer me a question?
I'm a first year doctor degree student in ajou university. I'm not familiar
with pytorch.
I think you know CE2P. it's original version can be executed on
Pytorch0.4.1.
now I want to transfer it from 0.4.1 to pytorch 1.3. readme of CE2P said
" use Pytorch 1.0, just replace 'libs' with 'modules' in [
https://github.com/mapillary/inplace_abn"
but when I did as it said I encountered compile problems.  I think you know
how to do with that.
will you please give me the concrete steps to use inplace_abn in CE2P?
Thank you very much!
Best Regards!



2019년 12월 19일 (목) 오전 9:16, peike <notifications@github.com>님이 작성:
