### ISSUE TITLE
Error while running simple_extractor.py

### ISSUE THREAD

**Issue by soumyajit123dev** [PeikeLi/Self-Correction-Human-Parsing#53]
I ran the following command

python simple_extractor.py --dataset 'lip' --input-dir 'images' --model-restore 'pretrained/exp-schp-201908261155-lip.pth' --output-dir 'output'

input image is kept inside images folder
pretrained model is kept inside pretrained folder

I am getting some errors. I do not know how to resolve these errors. Please see the errors below

![Screenshot from 2021-02-19 12-23-19](https://user-images.githubusercontent.com/77043036/108470863-971cf500-72b0-11eb-9d60-aa8014559f7a.png)
![Screenshot from 2021-02-19 12-45-54](https://user-images.githubusercontent.com/77043036/108470869-98e6b880-72b0-11eb-9551-2d75169245c4.png)
:

Let me know what is required to solve the errors

**Comment by jutanke** [comment]
@soumyajit123dev resetting pytorch to an older version solved the issue on my end:
```conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 -c pytorch```

**Comment by PeikeLi** [comment]
Please try to run the CoLab notebook following https://colab.research.google.com/drive/1JOwOPaChoc9GzyBi5FUEYTSaP2qxJl10?usp=sharing.
If this works for you, basically this is related to the environment configuration based on your circumstances.
