### ISSUE TITLE
Evaluate with CPU?

### ISSUE THREAD

**Issue by VyBui** [PeikeLi/Self-Correction-Human-Parsing#7]
Can the model be loaded by CPU?

**Comment by PeikeLi** [comment]
@VyBui 

This is the issue regarding simple pytorch usage.

You can refer to the links below by youself.

https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349/5
https://pytorch.org/tutorials/beginner/saving_loading_models.html

**Comment by VyBui** [comment]
@PeikeLi thank you, it helps. 
I am going to close this one but I have another question regarding to the name of the github.

- It is still confused to me because when we say "human parsing" is it supposed to mean hair, head, left - right arm, left-right leg. 
- However in the prediction there is clothes too. is it correct for the arms go all the way up to the shoulder instead of it is now hidden inside the clothes (Tshirt)? Do you know what I mean?

Anyway, great job on the work, really appreciated!

Vy
