### ISSUE TITLE
The effect of the wrong labels in LIP

### ISSUE THREAD

**Issue by zzw1123** [PeikeLi/Self-Correction-Human-Parsing#8]
@PeikeLi 
Hi, thanks for your contribution!
Have you evaluated the effect of the wrong labels on the performance?
E.g., what is the mIoU after the model trained with all the wrongly annotated images removed?

**Comment by PeikeLi** [comment]
The truth is that without 'perfect' ground truth, we cannot tell which part is wrong and which part is right. Our method aims to alleviate the noise label as much as possible implicitly.

I would like to suggest using some synthetic data (which have perfect labels) to better understand the effect.

**Comment by VyBui** [comment]
@PeikeLi @zzw1123 does semi-supervised mean that human has involved 50% of the work in the process?

My suggestion is to have somebody to label 20-30% the dataset first, then increase the amount of 'perfect' ground truth over time. What do you think?

**Comment by PeikeLi** [comment]
Temporarily closed due to inactivating.
