### ISSUE TITLE
Extract part feature

### ISSUE THREAD

**Issue by ctrcv** [PeikeLi/Self-Correction-Human-Parsing#9]
Hi，I want to know how I can get human part feature in intermediate layers, because the feature maps after Decoder have been the shape of (class_num, w, h) in your model.
I am a newbie in deep learning, maybe my question is silly, but I really want to get your help, thanks!

**Comment by PeikeLi** [comment]
If you want to get the intermediate features, just return the value of the layer you need in the corresponding function.

I'll close the issue temporarily.
